//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Refferal_of_patients
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Hospitalization = new HashSet<Hospitalization>();
            this.TherapMeasures = new HashSet<TherapMeasures>();
        }
    
        public int PatientId { get; set; }
        public string Photo { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string MiddleName { get; set; }
        public string PassportNumSerial { get; set; }
        public System.DateTime Birthday { get; set; }
        public int Gender { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public string MedCardNum { get; set; }
        public System.DateTime MedCardDate { get; set; }
        public System.DateTime LastVizitDate { get; set; }
        public Nullable<System.DateTime> NextVizitDate { get; set; }
        public string PolisNum { get; set; }
        public System.DateTime PolisDate { get; set; }
        public string Diagnose { get; set; }
        public string MedicalHistory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hospitalization> Hospitalization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TherapMeasures> TherapMeasures { get; set; }
    }
}
