//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Refferal_of_patients
{
    using System;
    using System.Collections.Generic;
    
    public partial class TherapMeasures
    {
        public int MeasureId { get; set; }
        public int PatientId { get; set; }
        public System.DateTime EventDate { get; set; }
        public string Doctor { get; set; }
        public int Event { get; set; }
        public string EventName { get; set; }
        public string Results { get; set; }
        public string Recomendations { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
